config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create, :destroy]
  resources :blogs, only: [:index, :new, :create, :destroy] do
    resources :comments, only: [:create, :destroy]
  end
  root "users#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  # アソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy

  # バリデーション
  validates :title, presence: true
  validates :body, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  # アソシエーション
  belongs_to :blog
  belongs_to :user

  # バリデーション
  validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # アソシエーション
  has_many :blogs, dependent: :destroy
  has_many :comments, dependent: :destroy

  # バリデーション
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
    @blogs = Blog.all
    @users = User.all
    @comment = Comment.new
  end

  def new
    @blog = Blog.new
    @users = User.all
  end

  def create
    current_user = User.find_by(id: user_params[:id])
    @blog = current_user.blogs.build(blog_params)
    if @blog.save
      flash[:success] = "ブログを作成しました。"
      redirect_to blogs_path
    else
      @users = User.all
      render "new"
    end
  end

  def destroy
    Blog.find(params[:id]).destroy
    flash[:success] = "ブログを削除しました"
    redirect_to blogs_path
  end

  private
    def blog_params
      params.require(:blog).permit(:title, :body)
    end

    def user_params
      params.require(:user).permit(:id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    current_user = User.find_by(id: user_params[:id])
    blog = Blog.find_by(id: blog_params[:blog_id])
    @comment = current_user.comments.build(comment_params)
    @comment.blog_id = blog.id
    if @comment.save
      flash[:success] = "コメントを投稿しました。"
      redirect_to blogs_path
    else
      flash[:alert] = "コメントの投稿に失敗しました。"
      @blogs = Blog.all
      @users = User.all
      render "blogs/index"
    end
  end

  def destroy
    Comment.find(params[:id]).destroy
    flash[:success] = "コメントを削除しました"
    redirect_to blogs_path
  end

  private
    def comment_params
      params.require(:comment).permit(:body)
    end

    def user_params
      params.require(:user).permit(:id)
    end

    def blog_params
      params.permit(:blog_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "ユーザーを作成しました。"
      redirect_to users_path
    else
      render "new"
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "ユーザーを削除しました"
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/index.html.erb
<%= render "layouts/flash_message" %>
<h1>Blogs#index</h1>
<%= render "layouts/link" %>

<h2>投稿されたブログ</h2>
<ul>
  <% @blogs.each do |blog| %>
    <li class="blog_wrap">
      <h3>タイトル: <%= blog.title %></h3>
      <div class="blog_body">本文: <%= blog.body %></div>
      <p>ユーザー名: <%= blog.user.name %></p>
      <%= link_to "ブログ削除", blog_path(blog.id), data: { confirm: "本当に削除しますか？" },
       method: :delete %>
    </li>
    <%= render "layouts/comment_list", blog: blog %>

    <%= render "layouts/comment_form", blog: blog %>
  <% end %>
</ul>

app/views/blogs/new.html.erb
<h1>Blogs#new</h1>
<%= render "layouts/link" %>

<h2>新規ブログ作成</h2>
<% if @users.blank? %>
  <p>ユーザーを一人以上作成して下さい。</p>
<% else %>
  <%= form_with model: @blog, local: true do |f| %>
    <p class="form_label"><%= f.label :title %><span class="required">必須</span></p>
    <%= f.text_field :title %>
    <%= render "layouts/error_messages", model: @blog, attribute: :title %>

    <p class="form_label"><%= f.label :body %><span class="required">必須</span></p>
    <%= f.text_area :body %>
    <%= render "layouts/error_messages", model: @blog, attribute: :body %>

    <div class="current_user">
      <%= collection_select :user, :id, @users, :id, :name, required: true %>
      <label>ブログを投稿するユーザーを選択してください。</label>
    </div>

    <div class="button">
      <%= f.submit "投稿" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_comment_form.html.erb
<%= form_with model: @comment, url: blog_comments_path(blog_id: blog.id), local: true do |f|  %>
  <%= f.text_area :body, placeholder: "コメントを入力してください", required: true %>
  <%= render "layouts/error_messages", model: @comment, attribute: :body %>

  <div class="current_user">
    <span>
      <%= collection_select :user, :id, @users, :id, :name %><label>コメントを投稿するユーザーを選択してください。</label>
    </span>
  </div>

  <span class="button">
    <%= f.submit "コメント投稿" %>
  </span>
<% end %>

app/views/layouts/_comment_list.html.erb
<ul>
  <% if blog.comments.present? %>
    <% blog.comments.each do |comment| %>
        <li>
          <%= comment.body %> by <%= comment.user.name %>
          <%= link_to "コメント削除", blog_comment_path(blog_id: blog.id, id: comment.id),
          data: { confirm: "本当に削除しますか？" }, method: :delete %>
        </li>
    <% end %>
  <% else %>
    <p>コメントがありません。</p>
  <% end %>
</ul>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <span class="alert alert-warning">
    <% model.errors.full_messages_for(attribute).each do |message| %>
      <%= message.html_safe %>
    <% end %>
  </span>
<% end %>

app/views/layouts/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" if msg.is_a?(String) %>
<% end %>

app/views/layouts/_link.html.erb
<div>
  <ul>
    <li><%= link_to "ユーザーの作成", new_user_path %></li>
    <li><%= link_to "ユーザー一覧", users_path %></li>
    <li><%= link_to "ブログの作成", new_blog_path %></li>
    <li><%= link_to "ブログ一覧", blogs_path %></li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CommentFunction</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<%= render "layouts/flash_message" %>
<h1>Users#index</h1>

<h2>登録済みのユーザー</h2>
<ul>
  <% @users.each do |user| %>
    <li>
      <span>ユーザー名: </span>
      <%= user.name %>
      <%= link_to "削除", user_path(user.id), data: { confirm: "本当に削除しますか？" },
       method: :delete %>
    </li>
  <% end %>
</ul>

<%= render "layouts/link" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<%= render "layouts/link" %>

<h2>新規ユーザー作成</h2>
<%= form_with model: @user, local: true do |f| %>
  <p class="form_label"><%= f.label :name %><span class="required">必須</span></p>
  <%= f.text_field :name %>
  <%= render "layouts/error_messages", model: @user, attribute: :name %>

  <div class="button">
    <%= f.submit "ユーザー作成" %>
  </div>
<% end %>